### ISSUE TITLE
 file is encrypted or is not a database:

### ISSUE THREAD

**Issue by ldlywt** [YiuChoi/crackTencent#2]
你好，请问这个报错怎么解决？
net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;

**Comment by keien411** [comment]
相同的错误

**Comment by keien411** [comment]
> 02-26 21:51:35.976 1506-1506/? I/art: Late-enabling -Xcheck:jni
02-26 21:51:35.989 1506-1506/? V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@c4ad195
02-26 21:51:36.047 1506-1506/name.caiyao.cracktencent I/libthemeutils: Theme： libthemeutil.so load success
02-26 21:51:36.154 1506-1506/name.caiyao.cracktencent I/InstantRun: starting instant run server: is main process
02-26 21:51:36.209 1506-1506/name.caiyao.cracktencent W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
02-26 21:51:36.229 1506-1537/name.caiyao.cracktencent W/System: ClassLoader referenced unknown path: /system/app/MiuiContentCatcher/lib/arm64
02-26 21:51:36.234 1506-1506/name.caiyao.cracktencent D/AccessibilityManager: current package=name.caiyao.cracktencent, accessibility manager mIsFinalEnabled=false, mOptimizeEnabled=true, mIsUiAutomationEnabled=false, mIsInterestedPackage=false
02-26 21:51:36.326 1506-1538/name.caiyao.cracktencent I/TAG: command run:cd /mnt/sdcard/
02-26 21:51:36.326 1506-1538/name.caiyao.cracktencent I/TAG: command run:mkdir cracktencent
02-26 21:51:36.326 1506-1538/name.caiyao.cracktencent I/TAG: command run:cd cracktencent
02-26 21:51:36.326 1506-1538/name.caiyao.cracktencent I/TAG: command run:mkdir qq
02-26 21:51:36.326 1506-1538/name.caiyao.cracktencent I/TAG: command run:mkdir weixin
02-26 21:51:36.351 1506-1547/name.caiyao.cracktencent I/Adreno: QUALCOMM build                   : 4f3d4bc, I07a8b16b27
                                                                Build Date                       : 10/26/17
                                                                OpenGL ES Shader Compiler Version: XE031.09.00.04
                                                                Local Branch                     : mybranch28842968
                                                                Remote Branch                    : quic/gfx-adreno.lnx.1.0.r5-rel
                                                                Remote Branch                    : NONE
                                                                Reconstruct Branch               : NOTHING
02-26 21:51:36.355 1506-1547/name.caiyao.cracktencent I/OpenGLRenderer: Initialized EGL, version 1.4
02-26 21:51:36.355 1506-1547/name.caiyao.cracktencent D/OpenGLRenderer: Swap behavior 1
02-26 21:51:36.374 1506-1538/name.caiyao.cracktencent I/TAG: command out:mkdir: 'cracktencent': File exists
02-26 21:51:36.383 1506-1538/name.caiyao.cracktencent I/TAG: command out:mkdir: 'qq': File exists
02-26 21:51:36.391 1506-1538/name.caiyao.cracktencent I/TAG: command out:mkdir: 'weixin': File exists
02-26 21:51:36.396 1506-1538/name.caiyao.cracktencent I/TAG: command run:chmod 777 /data/data/com.tencent.mobileqq/databases -R
02-26 21:51:36.452 1506-1538/name.caiyao.cracktencent I/TAG: command run:chmod 777 /data/data/com.tencent.mm/MicroMsg -R
02-26 21:51:36.453 1506-1538/name.caiyao.cracktencent I/TAG: command run:cat /data/data/com.tencent.mm/shared_prefs/system_config_prefs.xml > /data/data/name.caiyao.cracktencent/shared_prefs/system_config_prefs.xml
02-26 21:51:36.453 1506-1538/name.caiyao.cracktencent I/TAG: command run:chmod 777 /data/data/name.caiyao.cracktencent/shared_prefs/system_config_prefs.xml
02-26 21:51:36.552 1506-1586/name.caiyao.cracktencent W/SharedPreferencesImpl: getSharedPreferences
                                                                               java.io.FileNotFoundException: /data/user/0/name.caiyao.cracktencent/shared_prefs/system_config_prefs.xml (Permission denied)
                                                                                   at java.io.FileInputStream.open(Native Method)
                                                                                   at java.io.FileInputStream.<init>(FileInputStream.java:146)
                                                                                   at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java:119)
                                                                                   at android.app.SharedPreferencesImpl.-wrap1(SharedPreferencesImpl.java)
                                                                                   at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java:90)
02-26 21:51:36.553 1506-1538/name.caiyao.cracktencent I/TAG: weixin uid is :-833076470
02-26 21:51:36.553 1506-1538/name.caiyao.cracktencent I/TAG: key:863817037628388-833076470
02-26 21:51:36.553 1506-1538/name.caiyao.cracktencent I/TAG: pwd:ed5c720
02-26 21:51:36.556 1506-1538/name.caiyao.cracktencent I/TAG: command run:chmod 777 /data/data/com.tencent.mm/MicroMsg/ee1da3ae2100e09165c2e52382cfe79f/EnMicroMsg.db
02-26 21:51:36.556 1506-1538/name.caiyao.cracktencent I/TAG: command run:dd if=/data/data/com.tencent.mm/MicroMsg/ee1da3ae2100e09165c2e52382cfe79f/EnMicroMsg.db of=/mnt/sdcard/cracktencent/weixin/EnMicroMsg.db
02-26 21:51:36.585 1506-1538/name.caiyao.cracktencent I/TAG: command out:chmod: /data/data/com.tencent.mm/MicroMsg/ee1da3ae2100e09165c2e52382cfe79f/EnMicroMsg.db: No such file or directory
02-26 21:51:36.596 1506-1538/name.caiyao.cracktencent I/TAG: command out:dd: /data/data/com.tencent.mm/MicroMsg/ee1da3ae2100e09165c2e52382cfe79f/EnMicroMsg.db: No such file or directory
02-26 21:51:36.866 1506-1538/name.caiyao.cracktencent E/Database: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
                                                                  net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
                                                                      at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
                                                                      at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
                                                                      at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
                                                                      at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:83)
                                                                      at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:49)
                                                                      at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
                                                                      at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1787)
                                                                      at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1752)
                                                                      at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2427)
                                                                      at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2356)
                                                                      at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1116)
                                                                      at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1170)
                                                                      at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1165)
                                                                      at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1150)
                                                                      at name.caiyao.cracktencent.utils.Utils.copyDatabase(Utils.java:214)
                                                                      at name.caiyao.cracktencent.MainActivity$1.run(MainActivity.java:18)
02-26 21:51:36.867 1506-1538/name.caiyao.cracktencent E/AndroidRuntime: FATAL EXCEPTION: Thread-6
                                                                        Process: name.caiyao.cracktencent, PID: 1506
                                                                        net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
                                                                            at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
                                                                            at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
                                                                            at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
                                                                            at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:83)
                                                                            at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:49)
                                                                            at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
                                                                            at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1787)
                                                                            at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1752)
                                                                            at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2427)
                                                                            at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2356)
                                                                            at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1116)
                                                                            at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1170)
                                                                            at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1165)
                                                                            at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1150)
                                                                            at name.caiyao.cracktencent.utils.Utils.copyDatabase(Utils.java:214)
                                                                            at name.caiyao.cracktencent.MainActivity$1.run(MainActivity.java:18)
